runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /post_to_slack
  script: slack_worker.app
  login: admin

- url: /enqueue_next_pass_time
  script: passtimes_worker.app
  login: admin


libraries:
- name: flask
  version: "0.12"
- name: pytz
  version: "2017.2"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- enviroments/
- tests
